### ISSUE TITLE
Mx 6.9 seems to break the widget

### ISSUE THREAD

**Issue by SolvosNSA** [ivosturm/ColorPicker#3]
After converting my project from 6.8.1 to 6.9 the color picker widget broke giving the following error in the browser console:

mendix.sys.Data.get: error in handler for 8725724278032039: ColorPickerwidgetColorPicker0.applyContext: Error: ColorPickerwidgetColorPicker0.applyContext: TypeError: $ is not a function

**Comment by ivosturm** [comment]
The error message seems related to the fact that jQuery can not be found. Did you add jQuery to your project, i.e. by loading it via the index.html page?
