### ISSUE TITLE
Error in Mendix 7

### ISSUE THREAD

**Issue by dvdkroft** [ivosturm/ColorPicker#5]
After upgrading to Mendix 7, I get the following error:

> Uncaught Error: dojo.require and dojo.provide are not supported in Mendix 7. Please, use AMD style for custom widgets.
>     at Object.window.dojo.provide.window.dojo.require (mxui.js?636328744668879860:10)
>     at ColorPickerLibrary.js?636328744668879860:1

When trying to access the widget via a screen the progress bar just keeps on going and nothing happens.

**Comment by ivosturm** [comment]
I have just submitted version 1.3 of this widget in the public App Store of Mendix. It will probably be accepted by Mendix later this week. It contains an upgrade to Mendix 7 compatibility as well as two extra settings. See releasenotes.

**Comment by dvdkroft** [comment]
Thanks for the fast response, Ivo.

**Comment by ivosturm** [comment]
This issue should be fixed with the newest available release in the Mendix App Store. Feel free to rate the widget if it works!
