### ISSUE TITLE
going wrong with multiple colorpickers (Mendix)

### ISSUE THREAD

**Issue by riclo** [ivosturm/ColorPicker#6]
with MENDIX:

I  have a page with 4 colorpickers. And when building up the page you will see that all colorpickers will get the same values as the first one.
And when selecting another color for let's say the third one.  It will lookokay onthe screen, each colorpicker will show the new selected color,  but when debugging you ill notice that all colorpickers gets the same value. (the last selected color).

Another issue:
Have a page with two tabs and place one colorpicker on each tab.
It will give weird responses ....

**Comment by ivosturm** [comment]
Fixed by the commit from Kevin Vlaanderen. I am now releasing v1.4.0 in the Mendix AppStore.
